# Generated by Django 5.0 on 2024-01-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_orderproduct_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
    ]
