# Generated by Django 5.0 on 2024-01-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_orderproduct_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
